#!/usr/bin/env python3
"""Build data/exercises.json: exercise -> muscle group(s) mapping.

Sources: Jeff Nippard "The Ultimate Exercise Guide" (authoritative per-muscle
choices) + exercises extracted from the Pure Bodybuilding programs (PPL,
Upper/Lower, Full Body) and The Essentials Program. Compound movements map to
2+ muscle groups per the avatar's 11 groups:
  chest, shoulders, back, biceps, triceps, forearms, core,
  quadriceps, hamstrings, glutes, calves
"""
import json

# muscle:list of muscles
M = {
    "chest": "chest",
    "shoulders": "shoulders",
    "back": "back",
    "biceps": "biceps",
    "triceps": "triceps",
    "forearms": "forearms",
    "core": "core",
    "quadriceps": "quadriceps",
    "hamstrings": "hamstrings",
    "glutes": "glutes",
    "calves": "calves",
}

# name -> (muscles, type)
EX = {
    # ===== Ultimate Exercise Guide anchors =====
    "Machine Chest Press": ([M["chest"]], "compound"),
    "Dumbbell Incline Press": ([M["chest"], M["shoulders"], M["triceps"]], "compound"),
    "Cable Lateral Raise": ([M["shoulders"]], "isolation"),
    "Lean-In Dumbbell Lateral Raise": ([M["shoulders"]], "isolation"),
    "Neutral-Grip Close-Grip Lat Pulldown": ([M["back"], M["biceps"]], "compound"),
    "Neutral-Grip Pull-Up": ([M["back"], M["biceps"]], "compound"),
    "Chest-Supported T-Bar Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Deficit Pendlay Row": ([M["back"], M["biceps"], M["shoulders"], M["hamstrings"]], "compound"),
    "Bayesian Cable Curl": ([M["biceps"]], "isolation"),
    "45-Degree Dumbbell Preacher Curl": ([M["biceps"]], "isolation"),
    "Overhead Cable Triceps Extension": ([M["triceps"]], "isolation"),
    "Skull Crusher": ([M["triceps"]], "isolation"),
    "Dumbbell Wrist Curl / Reverse Curl": ([M["forearms"]], "isolation"),
    "Wrist Roller": ([M["forearms"]], "isolation"),
    "Neck Curl / Extension": ([M["shoulders"]], "isolation"),
    "Trap-Bar Shrug": ([M["shoulders"]], "isolation"),
    "Wide-Grip Barbell Shrug": ([M["shoulders"]], "isolation"),
    "Cable Crunch": ([M["core"]], "isolation"),
    "Weight-Plate Crunch": ([M["core"]], "isolation"),
    "Good Morning": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Romanian Deadlift": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Conventional Deadlift": ([M["hamstrings"], M["glutes"], M["back"], M["quadriceps"]], "compound"),
    "Sumo Deadlift": ([M["hamstrings"], M["glutes"], M["back"], M["quadriceps"]], "compound"),
    "Hack Squat": ([M["quadriceps"], M["glutes"]], "compound"),
    "Barbell Back Squat": ([M["quadriceps"], M["glutes"], M["hamstrings"], M["core"]], "compound"),
    "Barbell Front Squat": ([M["quadriceps"], M["glutes"], M["core"]], "compound"),
    "Lunge": ([M["glutes"], M["quadriceps"], M["hamstrings"]], "compound"),
    "Hip Thrust": ([M["glutes"], M["hamstrings"]], "compound"),
    "Seated Leg Curl": ([M["hamstrings"]], "isolation"),
    "Nordic Ham Curl": ([M["hamstrings"]], "isolation"),
    "Standing Calf Raise": ([M["calves"]], "isolation"),
    "Leg Press Toe Press": ([M["calves"]], "isolation"),

    # ===== Push / Pull / Legs + Upper/Lower + Full Body exercises =====
    "Cross-Body Lat Pull-Around": ([M["back"], M["biceps"]], "compound"),
    "Snatch-Grip RDL": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Chest-Supported Machine Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Straight-Bar Lat Prayer": ([M["back"], M["biceps"]], "compound"),
    "Hammer Preacher Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Lying Paused Rope Face Pull": ([M["shoulders"], M["back"]], "isolation"),
    "Cuffed Behind-The-Back Lateral Raise": ([M["shoulders"]], "isolation"),
    "Low Incline Smith Machine Press": ([M["chest"], M["shoulders"], M["triceps"]], "compound"),
    "Pec Deck (w/ Integrated Partials)": ([M["chest"]], "isolation"),
    "Overhead Cable Triceps Extension (Bar)": ([M["triceps"]], "isolation"),
    "Triceps Pressdown (Bar)": ([M["triceps"]], "isolation"),
    "Seated Leg Curl": ([M["hamstrings"]], "isolation"),
    "Machine Hip Adduction": ([M["quadriceps"], M["glutes"]], "isolation"),
    "Leg Extension": ([M["quadriceps"]], "isolation"),
    "Leg Press Calf Press": ([M["calves"]], "isolation"),
    "Bayesian Cable Curl": ([M["biceps"]], "isolation"),
    "Seated DB French Press": ([M["triceps"]], "isolation"),
    "Bottom-2/3 Constant Tension Preacher Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Cable Triceps Kickback": ([M["triceps"]], "isolation"),
    "Roman Chair Leg Raise": ([M["core"]], "isolation"),
    "Super-ROM Overhand Cable Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Arms-Extended 45° Hyperextension": ([M["back"], M["hamstrings"], M["glutes"]], "compound"),
    "Lean-Back Lat Pulldown": ([M["back"], M["biceps"]], "compound"),
    "Inverse DB Zottman Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Cable Reverse Flye (Mechanical Dropset)": ([M["shoulders"], M["back"]], "isolation"),
    "Cable Paused Shrug-In": ([M["shoulders"]], "isolation"),
    "Machine Shoulder Press": ([M["shoulders"], M["triceps"]], "compound"),
    "Cross-Body Cable Y-Raise": ([M["shoulders"]], "isolation"),
    "Paused Assisted Dip": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Low-Incline Dumbbell Flye": ([M["chest"], M["shoulders"]], "isolation"),
    "Katana Triceps Extension": ([M["triceps"]], "isolation"),
    "Ab Wheel Rollout": ([M["core"], M["back"]], "compound"),
    "Lying Leg Curl": ([M["hamstrings"]], "isolation"),
    "Leg Press": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "Smith Machine Lunge": ([M["glutes"], M["quadriceps"], M["hamstrings"]], "compound"),
    "Sissy Squat": ([M["quadriceps"]], "isolation"),
    "Standing Calf Raise": ([M["calves"]], "isolation"),
    "Cable Skull Crusher": ([M["triceps"]], "isolation"),
    "Kneeling Overhead Cable Curl": ([M["biceps"]], "isolation"),
    "Triceps Diverging Pressdown (Long Rope or 2 Ropes)": ([M["triceps"]], "isolation"),
    "Incline DB Stretch-Curl": ([M["biceps"]], "isolation"),
    "Smith Machine JM Press": ([M["triceps"], M["chest"]], "compound"),
    "Lat-Focused Cable Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Paused Barbell RDL": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Chest-Supported T-Bar Row + Kelso Shrug": ([M["back"], M["shoulders"], M["biceps"]], "compound"),
    "N1-Style Short-Head Curl": ([M["biceps"]], "isolation"),
    "Reverse Pec Deck (w/ Integrated Partials)": ([M["shoulders"], M["back"]], "isolation"),
    "Low Incline DB Press": ([M["chest"], M["shoulders"], M["triceps"]], "compound"),
    "Dual-Cable Triceps Press": ([M["triceps"]], "isolation"),
    "Bent-Over Cable Pec Flye (w/ Integrated Partials)": ([M["chest"]], "isolation"),
    "Deficit Pushup": ([M["chest"], M["triceps"], M["shoulders"], M["core"]], "compound"),
    "Smith Machine Squat": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "DB Calf Jumps": ([M["calves"]], "compound"),
    "Slow-Eccentric EZ-Bar Skull Crusher": ([M["triceps"]], "isolation"),
    "Slow-Eccentric Bayesian Curl": ([M["biceps"]], "isolation"),
    "Reverse-Grip Cable Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Dual-Handle Lat Pulldown (Mid-back + Lats)": ([M["back"], M["biceps"]], "compound"),
    "Concentration Cable Curl": ([M["biceps"]], "isolation"),
    "Rear Delt 45° Cable Flye": ([M["shoulders"], M["back"]], "isolation"),
    "Seated DB Shoulder Press": ([M["shoulders"], M["triceps"]], "compound"),
    "Decline Machine Chest Press": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Stomach Vacuums": ([M["core"]], "isolation"),
    "Super-ROM DB Lateral Raise": ([M["shoulders"]], "isolation"),
    "Smith Machine Reverse Lunge": ([M["glutes"], M["quadriceps"], M["hamstrings"]], "compound"),
    "Machine Hip Abduction": ([M["glutes"]], "isolation"),
    "Hammer Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Medicine Ball Russian Twists": ([M["core"]], "isolation"),
    "Glute-Ham Raise": ([M["hamstrings"], M["glutes"]], "compound"),
    "Cable Triceps Kickback": ([M["triceps"]], "isolation"),
    "Slow-Eccentric DB RDL": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Single-arm Overhead Cable Triceps Extension": ([M["triceps"]], "isolation"),
    "Neutral-Grip Lat Pulldown": ([M["back"], M["biceps"]], "compound"),
    "Bent-Over Cable Pec Flye": ([M["chest"]], "isolation"),
    "Rear Delt 45° Cable Flye": ([M["shoulders"], M["back"]], "isolation"),

    # ===== The Essentials Program (2022) =====
    "Hack Squat (Heavy)": ([M["quadriceps"], M["glutes"]], "compound"),
    "Hack Squat (Back off)": ([M["quadriceps"], M["glutes"]], "compound"),
    "Incline DB Press": ([M["chest"], M["shoulders"], M["triceps"]], "compound"),
    "Seated Hamstring Curl": ([M["hamstrings"]], "isolation"),
    "T-Bar Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "DB Bicep Curl": ([M["biceps"]], "isolation"),
    "DB Lateral Raise": ([M["shoulders"]], "isolation"),
    "Flat DB Press (Heavy)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Flat DB Press (Back off)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Seated DB Shoulder Press": ([M["shoulders"], M["triceps"]], "compound"),
    "Seated Cable Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "EZ Bar Skull Crusher": ([M["triceps"]], "isolation"),
    "EZ Bar Curl": ([M["biceps"]], "isolation"),
    "Romanian Deadlift": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Leg Press": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "Leg Extension": ([M["quadriceps"]], "isolation"),
    "Seated Calf Raise": ([M["calves"]], "isolation"),
    "Incline Machine Press": ([M["chest"], M["shoulders"], M["triceps"]], "compound"),
    "Single-Leg Leg Press (Heavy)": ([M["quadriceps"], M["glutes"]], "compound"),
    "Single-Leg Leg Press (Back off)": ([M["quadriceps"], M["glutes"]], "compound"),
    "Pendlay Row": ([M["back"], M["biceps"], M["shoulders"], M["hamstrings"]], "compound"),
    "Glute-Ham Raise": ([M["hamstrings"], M["glutes"]], "compound"),
    "Spider Curl": ([M["biceps"]], "isolation"),
    "Cable Lateral Raise": ([M["shoulders"]], "isolation"),
    "Hanging Leg Raise": ([M["core"]], "isolation"),
    "Weighted Dip (Heavy)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Weighted Dip (Back off)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Incline Chest-Supported DB Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Standing DB Arnold Press": ([M["shoulders"], M["triceps"]], "compound"),
    "DB Incline Curl": ([M["biceps"]], "isolation"),
    "DB French Press": ([M["triceps"]], "isolation"),
    "DB Bulgarian Split Squat": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "DB Romanian Deadlift": ([M["hamstrings"], M["glutes"], M["back"]], "compound"),
    "Goblet Squat": ([M["quadriceps"], M["glutes"], M["core"]], "compound"),
    "Leg Press Toe Press": ([M["calves"]], "isolation"),
    "Machine Crunch": ([M["core"]], "isolation"),
    "Machine Squat (Heavy)": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "Machine Squat (Back off)": ([M["quadriceps"], M["glutes"], M["hamstrings"]], "compound"),
    "Nordic Ham Curl": ([M["hamstrings"]], "isolation"),
    "Meadows Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Inverse Zottman Curl": ([M["biceps"], M["forearms"]], "isolation"),
    "Machine Lateral Raise": ([M["shoulders"]], "isolation"),
    "Pec Deck": ([M["chest"]], "isolation"),
    "Machine Chest Press (Heavy)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Machine Chest Press (Back off)": ([M["chest"], M["triceps"], M["shoulders"]], "compound"),
    "Machine Pulldown": ([M["back"], M["biceps"]], "compound"),
    "Cable Shoulder Press": ([M["shoulders"], M["triceps"]], "compound"),
    "Helms DB Row": ([M["back"], M["biceps"], M["shoulders"]], "compound"),
    "Overhead Cable Triceps Extension": ([M["triceps"]], "isolation"),
    "Cable EZ Curl": ([M["biceps"]], "isolation"),
    "DB Walking Lunge": ([M["glutes"], M["quadriceps"], M["hamstrings"]], "compound"),
    "Standing Calf Raise": ([M["calves"]], "isolation"),
    "Plate-Weighted Crunch": ([M["core"]], "isolation"),
}

# Build JSON: dedupe by lowercased name, keep last mapping
seen = {}
for name, (muscles, etype) in EX.items():
    key = name.lower().strip()
    seen[key] = {"name": name, "muscles": muscles, "type": etype}

exercises = list(seen.values())
exercises.sort(key=lambda e: e["name"].lower())

out = {"source": "Jeff Nippard - The Ultimate Exercise Guide + Pure Bodybuilding programs",
       "generated": "2026-08-18",
       "groups": ["chest", "shoulders", "back", "biceps", "triceps", "forearms",
                  "core", "quadriceps", "hamstrings", "glutes", "calves"],
       "exercises": exercises}

path = "/home/techhub/health-avatar-app/data/exercises.json"
with open(path, "w") as f:
    json.dump(out, f, indent=2)

print(f"wrote {len(exercises)} exercises -> {path}")
